---
- hosts: Kubernetes
  user: ubuntu

  tasks:
    - name: Deploy app into k8s
      command: kubectl apply -f marve-app-deploy.yml


    - name: Create service for the app
      command: kubectl apply -f marve-app-service.yml

    - name: Rollout deployment with new pods if image update on dockerhub
      command:  kubectl rollout restart deployment.apps/marve-app

