apiVersion: v1
kind: Service
metadata:
  name: marve-app-service
  labels:
    app: marve-app
spec:
  selector:
    app: marve-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
