apiVersion: apps/v1 
kind: Deployment
metadata:
  name: marve-app
  labels:
     app: marve-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: marve-app

  template:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marve-app
  labels:
     app: marve-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: marve-app

  template:
    metadata:
      labels:
        app: marve-app
    spec:
      containers:
      - name: marve-app
        image: marviflame89/marve-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
